name: "Build and deploy to github pages"

on:
  push:
    branches:
      - main  # Set a branch to deploy
    paths:
      - adblock.txt
      - hosts.txt
      - .github/workflows/deploy-to-github-pages.yml
jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    env:
      TARGET: ./public

    steps:
      - name: "Checkout Source"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Remove gitignore"
        run: rm -f "${{env.TARGET}}/.gitignore"

      - name: "Build"
        run: |
          mkdir "${{env.TARGET}}/"
          cp adblock.txt "${{env.TARGET}}/adblock.txt"
          cp hosts.txt "${{env.TARGET}}/hosts.txt"

      - name: "Deploy"
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: "${{env.TARGET}}"
          cname: abp.markridgwell.com
